# Google Cloud Build config — deploys to Cloud Run
# Usage:
#   gcloud builds submit --config cloudbuild.yaml .
#
# Prerequisites:
#   1. Enable Cloud Run, Cloud Build, Artifact Registry APIs
#   2. Create an Artifact Registry Docker repo:
#      gcloud artifacts repositories create kairi --repository-format=docker --location=us-central1
#   3. Set secrets in Secret Manager:
#      gcloud secrets create github-app-id --data-file=...
#      gcloud secrets create github-private-key --data-file=...
#      gcloud secrets create github-webhook-secret --data-file=...
#      gcloud secrets create anthropic-api-key --data-file=...
#      gcloud secrets create postgres-url --data-file=<(echo "postgresql://user:pass@host:5432/kairi")
#   4. For Postgres, use Cloud SQL or any managed PostgreSQL (e.g., Neon, Supabase, Railway)

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: kairi
  _REPO: kairi

steps:
  # Build the Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:$COMMIT_SHA
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:latest
      - .

  # Push to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=3000
      - --memory=512Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=5
      - --set-secrets=GITHUB_APP_ID=github-app-id:latest,GITHUB_PRIVATE_KEY=github-private-key:latest,GITHUB_WEBHOOK_SECRET=github-webhook-secret:latest,ANTHROPIC_API_KEY=anthropic-api-key:latest,POSTGRES_URL=postgres-url:latest
      - --execution-environment=gen2

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:$COMMIT_SHA
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:latest
